// sistema-educativo-frontend/src/app/shared/components/public-layout/footer/footer.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { DataService } from '../../../../core/services/data_general/data.service';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

 private readonly dataService = inject(DataService);

  readonly schoolInfo = this.dataService.schoolInfo;
  readonly yearsOfExperience = this.dataService.yearsOfExperience;
  readonly currentYear = new Date().getFullYear();

  readonly quickLinks = [
    { label: 'Inicio', route: '/' },
    { label: 'Proceso de Admisión', route: '/admision' },
    { label: 'Plana Docente', route: '/docentes' },
    { label: 'Noticias y Eventos', route: '/noticias' },
    { label: 'Contáctanos', route: '/contacto' }
  ];
}

<footer class="bg-gradient-to-br from-gray-900 via-blue-900 to-purple-900 text-white">
      <!-- Main Footer Content -->
      <div class="container-custom py-16">
        <div class="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
          <!-- Información del Colegio -->
          <div>
            <div class="flex items-center space-x-3 mb-6">
              <div class="w-12 h-12 bg-gradient-to-br from-blue-400 to-purple-400 rounded-xl flex items-center justify-center">
                <svg class="w-7 h-7 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l9-5-9-5-9 5 9 5z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z" />
                </svg>
              </div>
              <div>
                <h3 class="text-xl font-bold">{{ schoolInfo().name }}</h3>
                <p class="text-sm text-gray-300">{{ schoolInfo().slogan }}</p>
              </div>
            </div>
            <p class="text-gray-300 text-sm leading-relaxed mb-4">
              Formando líderes con excelencia académica y valores sólidos desde hace más de {{ yearsOfExperience() }} años.
            </p>
            <div class="flex space-x-3">
              <a 
                [href]="schoolInfo().socialMedia.facebook" 
                target="_blank"
                rel="noopener noreferrer"
                class="w-10 h-10 bg-white/10 hover:bg-blue-600 rounded-lg flex items-center justify-center transition-all duration-300 transform hover:scale-110"
                aria-label="Facebook"
              >
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                </svg>
              </a>
              <a 
                [href]="schoolInfo().socialMedia.instagram" 
                target="_blank"
                rel="noopener noreferrer"
                class="w-10 h-10 bg-white/10 hover:bg-pink-600 rounded-lg flex items-center justify-center transition-all duration-300 transform hover:scale-110"
                aria-label="Instagram"
              >
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zm0 5.838c-3.403 0-6.162 2.759-6.162 6.162s2.759 6.163 6.162 6.163 6.162-2.759 6.162-6.163c0-3.403-2.759-6.162-6.162-6.162zm0 10.162c-2.209 0-4-1.79-4-4 0-2.209 1.791-4 4-4s4 1.791 4 4c0 2.21-1.791 4-4 4zm6.406-11.845c-.796 0-1.441.645-1.441 1.44s.645 1.44 1.441 1.44c.795 0 1.439-.645 1.439-1.44s-.644-1.44-1.439-1.44z"/>
                </svg>
              </a>
              <a 
                [href]="schoolInfo().socialMedia.youtube" 
                target="_blank"
                rel="noopener noreferrer"
                class="w-10 h-10 bg-white/10 hover:bg-red-600 rounded-lg flex items-center justify-center transition-all duration-300 transform hover:scale-110"
                aria-label="YouTube"
              >
                <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/>
                </svg>
              </a>
            </div>
          </div>

          <!-- Enlaces Rápidos -->
          <div>
            <h4 class="text-lg font-bold mb-6">Enlaces Rápidos</h4>
            <ul class="space-y-3">
              <li *ngFor="let link of quickLinks">
                <a 
                  [routerLink]="link.route" 
                  class="text-gray-300 hover:text-white transition-colors duration-200 flex items-center group"
                >
                  <svg class="w-4 h-4 mr-2 transform group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                  </svg>
                  {{ link.label }}
                </a>
              </li>
            </ul>
          </div>

          <!-- Niveles Educativos -->
          <div>
            <h4 class="text-lg font-bold mb-6">Niveles Educativos</h4>
            <ul class="space-y-3">
              <li>
                <a routerLink="/niveles/inicial" class="text-gray-300 hover:text-white transition-colors duration-200 flex items-center group">
                  <span class="mr-2">🎨</span>
                  Inicial (3-5 años)
                </a>
              </li>
              <li>
                <a routerLink="/niveles/primaria" class="text-gray-300 hover:text-white transition-colors duration-200 flex items-center group">
                  <span class="mr-2">📚</span>
                  Primaria (6-11 años)
                </a>
              </li>
              <li>
                <a routerLink="/niveles/secundaria" class="text-gray-300 hover:text-white transition-colors duration-200 flex items-center group">
                  <span class="mr-2">🎓</span>
                  Secundaria (12-16 años)
                </a>
              </li>
            </ul>
          </div>

          <!-- Contacto -->
          <div>
            <h4 class="text-lg font-bold mb-6">Contacto</h4>
            <ul class="space-y-4">
              <li class="flex items-start">
                <svg class="w-5 h-5 mr-3 mt-0.5 flex-shrink-0 text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
                <span class="text-gray-300 text-sm">{{ schoolInfo().address }}</span>
              </li>
              <li class="flex items-center">
                <svg class="w-5 h-5 mr-3 flex-shrink-0 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                </svg>
                <a [href]="'tel:' + schoolInfo().phone" class="text-gray-300 hover:text-white transition-colors text-sm">
                  {{ schoolInfo().phone }}
                </a>
              </li>
              <li class="flex items-center">
                <svg class="w-5 h-5 mr-3 flex-shrink-0 text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                <a [href]="'mailto:' + schoolInfo().email" class="text-gray-300 hover:text-white transition-colors text-sm">
                  {{ schoolInfo().email }}
                </a>
              </li>
              <li class="flex items-start">
                <svg class="w-5 h-5 mr-3 mt-0.5 flex-shrink-0 text-orange-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <div class="text-gray-300 text-sm">
                  <p>{{ schoolInfo().schedule.weekdays }}</p>
                  <p>{{ schoolInfo().schedule.saturday }}</p>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Bottom Bar -->
      <div class="border-t border-white/10">
        <div class="container-custom py-6">
          <div class="flex flex-col md:flex-row items-center justify-between gap-4">
            <p class="text-gray-400 text-sm text-center md:text-left">
              © {{ currentYear }} {{ schoolInfo().name }}. Todos los derechos reservados.
            </p>
            <div class="flex flex-wrap items-center gap-6 text-sm">
              <a routerLink="/transparencia" class="text-gray-400 hover:text-white transition-colors">
                Transparencia
              </a>
              <a href="#" class="text-gray-400 hover:text-white transition-colors">
                Términos y Condiciones
              </a>
              <a href="#" class="text-gray-400 hover:text-white transition-colors">
                Política de Privacidad
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>

// colegioscmat/src/components/layout/Footer.tsx
import { useNavigate } from 'react-router-dom';
import { GraduationCap, Mail, Phone, MapPin, Facebook, Instagram, Twitter, Youtube } from 'lucide-react';

export function Footer() {
  const navigate = useNavigate();
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-gray-900 text-gray-300">
      {/* Main Footer */}
      <div className="max-w-7xl mx-auto px-6 py-12">
        <div className="grid md:grid-cols-4 gap-8">
          {/* About */}
          <div>
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 bg-gradient-to-r from-[#0E3A8A] to-[#C81E1E] rounded-lg">
                <GraduationCap className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="text-white font-bold text-lg">Cermat School</h3>
                <p className="text-xs text-gray-400">Azángaro, Perú</p>
              </div>
            </div>
            <p className="text-sm text-gray-400 leading-relaxed mb-4">
              Institución educativa comprometida con la excelencia académica y la formación integral de nuestros estudiantes.
            </p>
            <div className="flex gap-3">
              <a
                href="https://facebook.com"
                target="_blank"
                rel="noopener noreferrer"
                className="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-blue-600 transition-colors"
                aria-label="Visitar página de Facebook"
              >
                <Facebook className="w-4 h-4" />
              </a>
              <a
                href="https://instagram.com"
                target="_blank"
                rel="noopener noreferrer"
                className="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-pink-600 transition-colors"
                aria-label="Visitar página de Instagram"
              >
                <Instagram className="w-4 h-4" />
              </a>
              <a
                href="https://twitter.com"
                target="_blank"
                rel="noopener noreferrer"
                className="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-blue-400 transition-colors"
                aria-label="Visitar página de Twitter"
              >
                <Twitter className="w-4 h-4" />
              </a>
              <a
                href="https://youtube.com"
                target="_blank"
                rel="noopener noreferrer"
                className="w-8 h-8 bg-gray-800 rounded-full flex items-center justify-center hover:bg-red-600 transition-colors"
                aria-label="Visitar canal de YouTube"
              >
                <Youtube className="w-4 h-4" />
              </a>
            </div>
          </div>

          {/* Enlaces Rápidos */}
          <div>
            <h4 className="text-white font-bold mb-4">Enlaces Rápidos</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <button
                  onClick={() => navigate('/')}
                  className="hover:text-white transition-colors"
                >
                  Inicio
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/niveles')}
                  className="hover:text-white transition-colors"
                >
                  Niveles Educativos
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/docentes')}
                  className="hover:text-white transition-colors"
                >
                  Nuestro Equipo
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/noticias')}
                  className="hover:text-white transition-colors"
                >
                  Noticias y Eventos
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/admisiones')}
                  className="hover:text-white transition-colors"
                >
                  Admisiones
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/contacto')}
                  className="hover:text-white transition-colors"
                >
                  Contacto
                </button>
              </li>
            </ul>
          </div>

          {/* Portal */}
          <div>
            <h4 className="text-white font-bold mb-4">Portal Educativo</h4>
            <ul className="space-y-2 text-sm">
              <li>
                <button
                  onClick={() => navigate('/login')}
                  className="hover:text-white transition-colors"
                >
                  Acceso al Portal
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/privacidad')}
                  className="hover:text-white transition-colors"
                >
                  Política de Privacidad
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/terminos')}
                  className="hover:text-white transition-colors"
                >
                  Términos y Condiciones
                </button>
              </li>
              <li>
                <button
                  onClick={() => navigate('/cookies')}
                  className="hover:text-white transition-colors"
                >
                  Política de Cookies
                </button>
              </li>
            </ul>
          </div>

          {/* Contacto */}
          <div>
            <h4 className="text-white font-bold mb-4">Contacto</h4>
            <ul className="space-y-3 text-sm">
              <li className="flex items-start gap-3">
                <MapPin className="w-5 h-5 flex-shrink-0 mt-0.5" />
                <span>Jr. Educación 123, Azángaro, Puno, Perú</span>
              </li>
              <li className="flex items-center gap-3">
                <Phone className="w-5 h-5 flex-shrink-0" />
                <a href="tel:+51951234567" className="hover:text-white transition-colors">
                  +51 951 234 567
                </a>
              </li>
              <li className="flex items-center gap-3">
                <Mail className="w-5 h-5 flex-shrink-0" />
                <a href="mailto:contacto@cermatschool.edu.pe" className="hover:text-white transition-colors">
                  contacto@cermatschool.edu.pe
                </a>
              </li>
            </ul>
            <div className="mt-4 p-3 bg-gray-800 rounded-lg">
              <p className="text-xs text-gray-400">
                <strong className="text-white">Horario:</strong><br />
                Lun - Vie: 8:00 AM - 6:00 PM<br />
                Sábados: 9:00 AM - 1:00 PM
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Bar */}
      <div className="border-t border-gray-800">
        <div className="max-w-7xl mx-auto px-6 py-6">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-sm text-gray-400">
              © {currentYear} Cermat School. Todos los derechos reservados.
            </p>
            <div className="flex flex-wrap items-center gap-4 text-xs text-gray-400">
              <button
                onClick={() => navigate('/privacidad')}
                className="hover:text-white transition-colors"
              >
                Privacidad
              </button>
              <span>•</span>
              <button
                onClick={() => navigate('/terminos')}
                className="hover:text-white transition-colors"
              >
                Términos
              </button>
              <span>•</span>
              <button
                onClick={() => navigate('/cookies')}
                className="hover:text-white transition-colors"
              >
                Cookies
              </button>
              <span>•</span>
              <span>Hecho con ❤️ en Perú</span>
            </div>
          </div>
        </div>
      </div>
    </footer>
  );
}
